"""
[engine.py](https://engine.py/) — The core event loop of VELOX.

This is the central nervous system. It drives time forward
bar by bar, routes events between components, and ensures
strict temporal ordering — no component can see the future.

Architecture:
DataHandler   →  MarketEvent
Strategy      →  SignalEvent
Portfolio     →  OrderEvent
Execution     →  FillEvent
Portfolio     ←  FillEvent (updates positions)
"""

import queue
import logging
from datetime import datetime
from typing import List

from core.events import EventType, MarketEvent

logger = logging.getLogger(__name__)


class Engine:
    """
    The backtesting engine. Drives the event loop.
    In backtesting mode:   runs as fast as possible through historical data
    In live trading mode:  same loop, but DataHandler blocks waiting for
                           real market ticks — zero other code changes needed.

    This is the key architectural win: live trading is just
    a different DataHandler. Everything else is identical.
    """

    def __init__(
        self,
        data_handler,
        strategies: List,
        portfolio,
        execution_handler,
        risk_manager=None,
    ):

        self.data = data_handler
        self.strategies = strategies
        self.portfolio = portfolio
        self.execution = execution_handler
        self.risk = risk_manager


        # The central event queue — every component reads/writes here
        self.events: queue.Queue = queue.Queue()

        self.running = False
        self.bar_count = 0

        # Wire up the queue to every component
        self.data.events = self.events
        self.portfolio.events = self.events
        self.execution.events = self.events
        for strategy in self.strategies:
            strategy.events = self.events

    # ─── Main Loop ────────────────────────────────────────────────────────────

    def run(self) -> None:
        """
        Start the engine. Runs until data is exhausted.

        The loop has two levels:
          Outer loop: advances the clock one bar at a time
          Inner loop: drains all events generated by that bar
                      before moving to the next bar
        """
        logger.info("VELOX engine starting...")
        self.running = True
        start_time = datetime.utcnow()

        while self.running:

            # ── Outer loop: advance one bar ────────────────────────────────
            if self.data.has_next():
                self.data.update_bars()  # loads next bar, fires MarketEvent
                self.bar_count += 1
            else:
                logger.info(f"Data exhausted after {self.bar_count} bars.")
                self.running = False
                break

            # ── Inner loop: drain all events from this bar ─────────────────
            while True:
                try:
                    event = self.events.get(block=False)
                except queue.Empty:
                    break  # no more events for this bar, advance clock

                if event is None:
                    continue

                self._route(event)

        elapsed = (datetime.utcnow() - start_time).total_seconds()
        logger.info(
            f"Backtest complete. {self.bar_count} bars in {elapsed:.2f}s."
        )
        self._finish()

    # ─── Event Router ─────────────────────────────────────────────────────────

    def _route(self, event) -> None:
        """
        Routes each event to the correct handler.

        This is a pure dispatcher — it knows nothing about
        what any handler does, just who handles what.
        """
        match event.type:

            case EventType.MARKET:
                # New bar arrived — wake up all strategies
                for strategy in self.strategies:
                    strategy.on_market(event)
                # Record equity on every bar for a complete chart
                self.portfolio._update_equity(event.timestamp)

            case EventType.SIGNAL:
                # Strategy saw an opportunity — portfolio decides action
                self.portfolio.on_signal(event)

            case EventType.ORDER:

                # If we have a risk manager, validate the order
                if self.risk is not None:
                    approved = self.risk.validate(event)

                    if not approved:
                        logger.info(
                            f"Order rejected by risk manager: "
                            f"{event.direction.value} {event.quantity} {event.symbol}"
                        )
                        return

                # Order passed risk checks
                self.execution.on_order(event)


            case EventType.FILL:
                # Order filled — portfolio updates positions and cash
                self.portfolio.on_fill(event)

            case _:
                logger.warning(f"Unknown event type: {event.type}")

    # ─── Teardown ─────────────────────────────────────────────────────────────

    def _finish(self) -> None:
        """
        Called when the backtest ends.
        Triggers performance calculation in the portfolio.
        """
        logger.info("Computing performance metrics...")
        self.portfolio.compute_metrics()
        logger.info("Done. Access results via engine.portfolio.metrics")